// eslint-disable-next-line @typescript-eslint/naming-convention
export enum TOKEN_NAMES {
  BNB = 'BNB',
  USDT = 'USDT',
  BUSD = 'BUSD',
  USDC = 'USDC',
  SXP = 'SXP',
  XVS = 'XVS',
  BANANA = 'BANANA',
  ETH = 'ETH',
  DAI = 'DAI',
  FIL = 'FIL',
  CAKE = 'CAKE',
  ADA = 'ADA',
  MATIC = 'MATIC',
  DOGE = 'DOGE',
  LTC = 'LTC',
  BCH = 'BCH',
  BETH = 'BETH',
  BLID = 'BLID',
  TUSD = 'TUSD',
  DOT = 'DOT',
  TRX = 'TRX',
  LINK = 'LINK',
  BTC = 'BTC',
  XRP = 'XRP',
  BSW = 'BSW',
}
