// eslint-disable-next-line @typescript-eslint/naming-convention
export enum LBF_BULL_EVENTS {
  STRATEGY_AND_CLAIM_JOB = 'STRATEGY_AND_CLAIM_JOB',
  ADMIN_BALANCE_CRON_JOB = 'ADMIN_BALANCE_CRON_JOB',
  ANALYTICS_CRON_JOB = 'ANALYTICS_CRON_JOB',
  MONITORING_BOOSTING_BLID_BALANCES_CRON_NAME = 'MONITORING_BOOSTING_BLID_BALANCES_CRON_NAME',
}
